### PR TITLE
fix: primitives rendering to equal react output

### PR DESCRIPTION
**Pull request by damiennl**
Hello 👋,

I've just removed the boolean convert to string in order to write some JSX code like this:
```tsx
<>
  {flash.has('error'} && <span>{flash.get('error')}</span>}
</>
```
Because it could shows `false` which is not expected

It is by the way a regression because it was the behavior in v3.1.2

Thx 🙏

### CODE REVIEW

**Comment by arthurfiorette** [comment]
Hey @damiennl this was a regression of v3 because in v4 it now follows the exactly same behavior as React.

**Comment by arthurfiorette** [comment]
@JacopoPatroclo what's you thoughts on this?

**Comment by JacopoPatroclo** [comment]
@arthurfiorette The changes are sane. I agree with @damiennl that if you want to write something like this it's important that the boolean values are not rendered as strings. It makes the library more similar to React (and other jsx renderers) and I think it's a good thing.

I will also advise @damiennl to make sure to never put untrusted strings inside flash messages and/or escape them (using the primitive that this library gives you).

Thanks for the contribution @damiennl !

**Comment by arthurfiorette** [comment]
It was indeed a regression/breaking change, that's why we are at 4.0.0 now. 

The only requirement is to follow what React does because React is a "baseline" for every JSX runtime. Does this regression follows react? If it doesn't then it's a bug and I'll merge this pr.

Can someone create a test / reproducible example so that we can test it out?

**Comment by tqhoughton** [comment]
Is there any update on this? This behavior makes it annoying to do conditional rendering in templates since all of your `condition && <Component />` conditions have to be `condition ? <Component /> : null` instead.

**Comment by arthurfiorette** [comment]
Sadly, I do not have enough time to implement this right now.

In case someone wants to help me out, these are the functions doing the "fauly" work:

https://github.com/kitajs/html/blob/5f68ce56c9ebe2c354c4feaf8c5c16ae04247439/packages/html/index.js#L379

https://github.com/kitajs/html/blob/5f68ce56c9ebe2c354c4feaf8c5c16ae04247439/packages/html/index.js#L426

**Comment by tqhoughton** [comment]
I may have some time to address this sometime this week, seems like at initial glance the issue is this line in each function: https://github.com/kitajs/html/blob/5f68ce56c9ebe2c354c4feaf8c5c16ae04247439/packages/html/index.js#L389

where `boolean` variables are getting automatically converted to strings without regard for the `false` case.

**Comment by damiennl** [comment]
Hey guys 👋
This is a MR, I already do the changes, please check it
I fixed the two functions and updated the unit tests

**Comment by arthurfiorette** [comment]
> Can someone create a test / reproducible example so that we can test it out?

https://github.com/kitajs/html/pull/190#issuecomment-2064112799

**Comment by alexgorbatchev** [comment]
> The only requirement is to follow what React does because React is a "baseline" for every JSX runtime. Does this regression follows react? If it doesn't then it's a bug and I'll merge this pr.

```jsx
react:  <>{false && 'hello'}</> -> ""
kitajs: <>{false && 'hello'}</> -> "false"
```

**Comment by arthurfiorette** [comment]
Hey @damiennl could you also remove booleans from the Children's type, now that both `true` and `false` renders to an empty string, the minimum we could do is warn the user about it.

**Comment by arthurfiorette** [comment]
I ended up re implementing this myself to exactly match what react renders to.

**Pull request merged**
