### PR TITLE
feat(html): add more attributes

### PR DESCRIPTION
**Pull request by douglasduteil**
Hi.

Will using `@kitajs/html` for mailing, I figure that there is some missing html attributes on some tags.

### CODE REVIEW

**Comment by arthurfiorette** [comment]
[valign is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement/vAlign)

**Comment by douglasduteil** [comment]
Yep. Making mails template compatibility is a mess...
One can relay on deprecated attributes to ensure that all clients get the table based madness right...  
https://www.caniemail.com/features/html-valign/

@arthurfiorette Should I remove this attribute ?

**Comment by arthurfiorette** [comment]
i think you can just add a `/** @deprecated */` to it :)

**Comment by douglasduteil** [comment]
Deal :handshake:

**Pull request merged**
